name: Docker Nightly

on:
  schedule:
    - cron: "0 2 * * *" # daily at 2:00 AM UTC
  workflow_dispatch: # manual trigger

jobs:
  publish-docker-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t qubiccore/bob:nightly -f docker/Dockerfile .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push qubiccore/bob:nightly
